### ISSUE TITLE
生成文档时候，希望可以读取文档的格式

### ISSUE THREAD

**Issue by xaoyaoo** [14790897/handwriting-web#15]
主要是居中、空格、首行缩进

**Comment by 14790897** [comment]
试试直接手动全选复制文档中的内容，然后粘贴到网页中？

**Comment by 14790897** [comment]
我发现先转换成PDF，然后上传PDF是可以保留原来格式的

**Comment by 14790897** [comment]
我做了一下docx的功能，等会上线
![image](https://github.com/14790897/handwriting-web/assets/121866954/ef7d08f0-6f05-40a2-bc70-a4c15ad521cd)

**Comment by 14790897** [comment]
已经上线
