### ISSUE TITLE
想制作一个这样的android app是需要用api吗，作者大大

### ISSUE THREAD

**Issue by lpwyz** [14790897/handwriting-web#34]
想制作一个这样的android app是需要用api吗，作者大大

**Comment by 14790897** [comment]
建议问GPT

**Comment by lpwyz** [comment]
> 需要

 那这个api咋写啊

**Comment by 14790897** [comment]
> > 需要
> 
> 那这个api咋写啊

参考后端代码：https://github.com/14790897/handwriting-web/blob/main/backend/app.py
