### ISSUE TITLE
需要透明背景

### ISSUE THREAD

**Issue by hmppt** [14790897/handwriting-web#37]
我需要一个透明背景，当我设置如下时，我最后获得的图像是一张完全透明不带有字符的图像，这是怎么回事？
![image](https://github.com/14790897/handwriting-web/assets/43752397/088550d2-2f71-4ba5-b4cd-f2f6a8f71c73)

**Comment by hmppt** [comment]
而且我在背景图为RGB图像的基础上，改字体颜色也毫无变化，似乎fill的参数固定是黑色的？
![image](https://github.com/14790897/handwriting-web/assets/43752397/d2e0d26b-9d50-40f4-954c-9fe183b67325)

**Comment by hmppt** [comment]
没事了，我发现fill没传进去：）

**Comment by 14790897** [comment]
😉
