### ISSUE TITLE
奇怪的斜线

### ISSUE THREAD

**Issue by Ntoskrnl2333** [14790897/handwriting-web#38]
![image](https://github.com/user-attachments/assets/53d0984d-ac1c-44ff-81c8-348122bc0d61)

有时会有这样奇怪的斜线，有的粗有的细，斜线下面的文字也被吞了或被修改了

**Comment by Ntoskrnl2333** [comment]
好像只有英文会这样？

**Comment by 14790897** [comment]
这个是模拟划掉错字
![image](https://github.com/user-attachments/assets/37eca2de-09a1-4602-96f0-68b37c7f2bc7)

**Comment by 14790897** [comment]
把概率改成0，就不会出现了
