### ISSUE TITLE
网址是不是寄了

### ISSUE THREAD

**Issue by yangyibufeng** [14790897/handwriting-web#6]
https://handwrite.liuweiqing.top/

**Comment by 14790897** [comment]
谢谢提醒，我修一下

**Comment by 14790897** [comment]
服务器宕机了，不知道怎么回事，现已恢复服务

**Comment by yangyibufeng** [comment]
ok,我去试试




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年9月30日(星期六) 晚上9:06
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [14790897/handwriting-web] 网址是不是寄了 (Issue #6)





 
服务器宕机了，不知道怎么回事，现已恢复服务
