### ISSUE TITLE
奶字会写成妈字

### ISSUE THREAD

**Issue by ethon-wang** [14790897/handwriting-web#7]

**Comment by 14790897** [comment]
![image](https://github.com/14790897/handwriting-web/assets/121866954/fa410956-9fd7-4c1f-a8c2-97b1055ec4e7)
这个软件实际上是通过改变笔画的旋转，大小，位置来模拟真实字迹，所以它不会有错字出现

**Comment by ethon-wang** [comment]
复现：华阳手写体，输入【亚奶】，生产【亚妈】

**Comment by ethon-wang** [comment]
> 复现：华阳手写体，输入【亚奶】，生产【亚妈】

是字体库原因吗

**Comment by 14790897** [comment]
![image](https://github.com/14790897/handwriting-web/assets/121866954/1615972e-bbbc-40fa-b323-d34142f290fe)
我这里也看到了，应该是字体库的原因

**Comment by ethon-wang** [comment]
十分感谢，神器

**Comment by 14790897** [comment]
好的，感谢支持
