### ISSUE TITLE
生成文字过多时，会发生超时错误，本地调试没问题，现在怀疑是gunicorn的问题

### ISSUE THREAD

**Issue by 14790897** [14790897/handwriting-web#8]

**Comment by 14790897** [comment]
等一下，那我只要多次分批生成不就行了？？？

**Comment by chigua2248** [comment]
大佬解决了吗

**Comment by 14790897** [comment]
> 大佬解决了吗

没有啊，觉得很麻烦

**Comment by 14790897** [comment]
> 大佬解决了吗

解决了


2024.6.13 由于昨天需要完成政治论文的手写，于是亲自体验了我的程序，发现效果确实不错，但是几个月来一直没有解决处理大量文字的时候程序没响应的问题，经过我添加日志发现，其实后端一直在生成图片，但是由于nginx的超时限制导致请求失败（这个在docker的日志中可以看到），于是我修改了外部和镜像内部的nginx的超时配置，但是问题仍然存在，这时我发现前端控制台中不再是504错误而是524错误，经过查询发现这是因为cf的超时限制是100秒，超过cf的限制而报错，解决方法是关闭小黄云不享受cf的保护，还有一种解决方法就是让后端不断给前端传输数据保持连接活跃。
